const C=window.MELAL_CONFIG,db=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY),A=document.getElementById("app"),logo="logo.jpg";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function siteHeader(x=""){return `<header class=top><div class=brand><img src="${logo}"><div><b>Melal English Language Institute</b><small>Online Examination Platform</small></div></div>${x}</header>`}
function speak(t){if(!speechSynthesis)return;let u=new SpeechSynthesisUtterance(t);u.lang="en-US";speechSynthesis.cancel();speechSynthesis.speak(u)}
async function user(){return (await db.auth.getUser()).data.user}
function nav(body,active){A.innerHTML=siteHeader('<button class="btn primary" onclick="logout()">Logout</button>')+`<div class=wrap><div class=layout><aside class="card side"><button class="${active=="home"?"active":""}" onclick=dashboard()>Dashboard</button><button class="${active=="exams"?"active":""}" onclick=exams()>Exams</button><button class="${active=="students"?"active":""}" onclick=students()>Students</button><button class="${active=="results"?"active":""}" onclick=results()>Results</button><button onclick=newExam()>＋ New Exam</button></aside><main>${body}</main></div></div>`}
function login(){A.innerHTML=siteHeader()+`<div class="card login"><div class=hero><img src="${logo}"><h2>Teacher / Admin Login</h2></div><label>Email</label><input id=email type=email><label>Password</label><input id=pass type=password><div class=actions><button class="btn primary" onclick=loginDo()>Login</button><button class="btn gold" onclick=signup()>Sign Up</button></div><p id=msg></p></div>`}
async function loginDo(){let e=email.value.trim(),p=pass.value;if(!e||!p)return msg.innerHTML='<span class=error>Please enter your email and password.</span>';let r=await db.auth.signInWithPassword({email:e,password:p});r.error?msg.innerHTML='<span class=error>'+esc(r.error.message)+'</span>':dashboard()}
async function signup(){let e=email.value.trim(),p=pass.value;if(!e||!p)return msg.innerHTML='<span class=error>Please enter an email and password.</span>';let r=await db.auth.signUp({email:e,password:p});msg.innerHTML=r.error?'<span class=error>'+esc(r.error.message)+'</span>':'<span class=success>Account created successfully.</span>'}
async function dashboard(){let u=await user();if(!u)return login();let[{data:e},{data:s}]=await Promise.all([db.from("exams").select("*").eq("owner_id",u.id),db.from("students").select("*").eq("owner_id",u.id)]);nav(`<div class=card><h2>Dashboard</h2><p class=muted>${esc(u.email)}</p><div class=stats><div class=stat>Exams<b>${e?.length||0}</b></div><div class=stat>Students<b>${s?.length||0}</b></div><div class=stat>Published<b>${e?.filter(x=>x.published).length||0}</b></div><div class=stat>English Audio<b>✓</b></div></div></div><div class="card" style="margin-top:15px"><h3>Exams</h3>${(e||[]).map(item).join("")||'<p class=muted>No exams yet.</p>'}</div>`,"home")}
function item(f){return `<div class=item><div class=itemhead><div><b>${esc(f.title)}</b><div class=muted>${esc(f.slug)}</div></div><span class=badge>${f.published?"Published":"Draft"}</span></div><div class=actions><button class="btn primary" onclick="editExam('${f.id}')">Edit</button><button class="btn gold" onclick="copyLink('${esc(f.slug)}')">Link</button><button class="btn soft" onclick="location.search='?exam='+encodeURIComponent('${esc(f.slug)}')">View</button></div></div>`}
async function exams(){let{data:e,error}=await db.from("exams").select("*").order("created_at",{ascending:false});if(error)return alert(error.message);nav(`<div class=card><div class=itemhead><h2>Exams</h2><button class="btn gold" onclick=newExam()>＋ New Exam</button></div>${(e||[]).map(item).join("")||'<p class=muted>No exams yet.</p>'}</div>`,"exams")}
async function newExam(){let u=await user(),t=prompt("Exam title","English File Elementary");if(!t)return;let slug=t.toLowerCase().replace(/[^a-z0-9]+/g,"-")+"-"+Math.random().toString(36).slice(2,6),r=await db.from("exams").insert({owner_id:u.id,title:t,slug,publis
